In [4]:
filename = './原书代码数据/chapter13/demo/data/data1.csv'
f = open(filename,'r',encoding='utf8')
data = pd.read_csv(f,sep=',')
f.close()

In [15]:
data.describe().T.applymap(lambda x : '{:.4f}'.format(x))

,count,mean,std,min,25%,50%,75%,max
x1,20.0000,5579519.9500,1262194.7236,3831732.0000,4525116.7500,5308896.5000,6594657.5000,7599295.0000
x2,20.0000,765.0350,595.6983,181.5400,302.2200,565.9400,1033.5350,2110.7800
x3,20.0000,2370.8250,1919.1668,448.1900,976.6600,1586.0200,3294.4850,6882.8500
x4,20.0000,19644.6850,10203.0217,7571.0000,11827.8150,15943.3750,25889.9375,42049.1400
x5,20.0000,15870.9480,8199.7714,6212.7000,9669.1625,12345.7050,21332.1850,33156.8300
x6,20.0000,7350513.6000,621341.8537,6370241.0000,6822868.0000,7314304.0000,7867809.7500,8323096.0000
x7,20.0000,1712.2390,1184.7138,525.7100,848.4025,1262.0500,2244.1175,4454.5500
x8,20.0000,5705.7990,4478.4002,985.3100,2077.7650,4104.5850,8500.0875,15420.1400
x9,20.0000,129.4935,50.5098,60.6200,91.8575,113.5300,169.9625,228.4600
x10,20.0000,340.2165,251.5779,65.6600,143.2375,235.7600,521.0650,852.5600
x11,20.0000,103.3050,5.5133,97.5000,99.8000,102.4500,103.9250,120.0000
x12,20.0000,1.4222,0.2532,1.0290,1.1995,1.4560,1.5782,1.9060
x13,20.0000,17273.8000,11109.1889,5321.0000,8418.5000,13267.0000,22633.0000,41972.0000
y,20.0000,618.0840,609.2545,64.8700,175.4350,319.5000,909.2725,2088.1400